### ISSUE TITLE
Plain IP in loadtab isn't working

### ISSUE THREAD

**Issue by i-vovk** [build2/brep#1]
Hello, I'm trying to deploy my own private brep instance. There isn't much information, so I'm using `INSTALL`/`INSTALL-DEV` and `etc/private/install/` files as a reference.

I'm not sure how properly write `loadtab` file, so I'm using `brep-startup` generated one. It turns out if the repo URL has IP instead of hostname, `brep-load` would take it:

```
$ whoami
brep
$ pwd
/home/brep
$ cat config/loadtab
http://127.0.0.1/1 private cache:/home/brep/bpkg/pkg/1
$ install/bin/brep-load config/loadtab
/home/brep/config/loadtab:1:1: error: relative filesystem path
```

If I change `127.0.0.1` to a valid hostname, e.g. 'localhost', `brep-load` processes it just fine:

```
$ sed -i "s/127.0.0.1/localhost/g" config/loadtab
$ cat config/loadtab
http://localhost/1 private cache:/home/brep/bpkg/pkg/1
$ install/bin/brep-load config/loadtab
$ echo $?
0
```

Am I missing something or is it a bug?

**Comment by karen-arutyunov** [comment]
Support for IP4/6 host types in repository URLs is added in 0.14.0 version of the toolchain. 

If you are setting up brep by following instructions in the INSTALL file, then consider installing brep from https://stage.build2.org/1 repository rather than from https://pkg.cppget.org/1/alpha.

**Comment by i-vovk** [comment]
Thanks, using 0.14.0 helped
